version: '3.3'
services:
  bellscoind:
    image: sandshrewmetaprotocols/bellscoin
    entrypoint: ["bells_oneshot"]
    command: ["-txindex", "-rpcbind=0.0.0.0"]
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - 0.0.0.0:19919:19919
      - 127.0.0.1:19918:19918
    volumes:
      - ${BELLSCOIN_DATA}:/bellscoin/.bellscoin
