version: '3.3'
services:
  bellscoind:
    image: sandshrewmetaprotocols/bellscoin
    entrypoint: ["bells_oneshot"]
    command: ["-txindex", "-rpcbind=0.0.0.0", "-rpcuser=bellscoinrpc", "-rpcpassword=bellscoinrpc"]
    build:
      dockerfile: Dockerfile
      context: ./
    network_mode: 'host'
    volumes:
      - ${BELLSCOIN_DATA}:/bellscoin/.bells
